<?php

namespace Database\Seeders;

use App\Models\ChartTemplate;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Log;

class ChartTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $seeded = 0;
        $templates = [
            // ─── Wellness Visit ───
            [
                'name' => 'Wellness Visit',
                'description' => 'Comprehensive annual wellness/preventive visit template with vitals, review of systems, screening questions, assessment, and plan.',
                'visit_type' => 'wellness',
                'sort_order' => 1,
                'fields' => [
                    // Vitals section
                    [
                        'id' => 'vitals_bp_systolic',
                        'label' => 'Blood Pressure (Systolic)',
                        'type' => 'number',
                        'options' => null,
                        'required' => true,
                        'section' => 'Vitals',
                        'unit' => 'mmHg',
                        'reference_range' => ['min' => 90, 'max' => 120],
                    ],
                    [
                        'id' => 'vitals_bp_diastolic',
                        'label' => 'Blood Pressure (Diastolic)',
                        'type' => 'number',
                        'options' => null,
                        'required' => true,
                        'section' => 'Vitals',
                        'unit' => 'mmHg',
                        'reference_range' => ['min' => 60, 'max' => 80],
                    ],
                    [
                        'id' => 'vitals_heart_rate',
                        'label' => 'Heart Rate',
                        'type' => 'number',
                        'options' => null,
                        'required' => true,
                        'section' => 'Vitals',
                        'unit' => 'bpm',
                        'reference_range' => ['min' => 60, 'max' => 100],
                    ],
                    [
                        'id' => 'vitals_temperature',
                        'label' => 'Temperature',
                        'type' => 'number',
                        'options' => null,
                        'required' => true,
                        'section' => 'Vitals',
                        'unit' => '°F',
                        'reference_range' => ['min' => 97.0, 'max' => 99.0],
                    ],
                    [
                        'id' => 'vitals_weight',
                        'label' => 'Weight',
                        'type' => 'number',
                        'options' => null,
                        'required' => true,
                        'section' => 'Vitals',
                        'unit' => 'lbs',
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'vitals_height',
                        'label' => 'Height',
                        'type' => 'number',
                        'options' => null,
                        'required' => true,
                        'section' => 'Vitals',
                        'unit' => 'in',
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'vitals_bmi',
                        'label' => 'BMI',
                        'type' => 'number',
                        'options' => null,
                        'required' => false,
                        'section' => 'Vitals',
                        'unit' => 'kg/m²',
                        'reference_range' => ['min' => 18.5, 'max' => 24.9],
                    ],
                    [
                        'id' => 'vitals_o2_sat',
                        'label' => 'O2 Saturation',
                        'type' => 'number',
                        'options' => null,
                        'required' => true,
                        'section' => 'Vitals',
                        'unit' => '%',
                        'reference_range' => ['min' => 95, 'max' => 100],
                    ],
                    // Review of Systems
                    [
                        'id' => 'ros_systems',
                        'label' => 'Review of Systems',
                        'type' => 'checkbox_group',
                        'options' => [
                            'Constitutional: No fever, weight loss, or fatigue',
                            'HEENT: No headaches, vision changes, or hearing loss',
                            'Cardiovascular: No chest pain, palpitations, or edema',
                            'Respiratory: No cough, dyspnea, or wheezing',
                            'GI: No nausea, vomiting, diarrhea, or abdominal pain',
                            'GU: No urinary frequency, urgency, or dysuria',
                            'Musculoskeletal: No joint pain, swelling, or stiffness',
                            'Neurological: No numbness, tingling, or weakness',
                            'Psychiatric: No depression, anxiety, or sleep disturbance',
                            'Skin: No rashes, lesions, or changes',
                        ],
                        'required' => true,
                        'section' => 'Review of Systems',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    // Screening Questions
                    [
                        'id' => 'screening_tobacco',
                        'label' => 'Tobacco Use',
                        'type' => 'select',
                        'options' => ['Never', 'Former', 'Current - light', 'Current - moderate', 'Current - heavy'],
                        'required' => true,
                        'section' => 'Screening',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'screening_alcohol',
                        'label' => 'Alcohol Use',
                        'type' => 'select',
                        'options' => ['None', 'Social/Occasional', 'Moderate', 'Heavy'],
                        'required' => true,
                        'section' => 'Screening',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'screening_exercise',
                        'label' => 'Exercise Frequency',
                        'type' => 'select',
                        'options' => ['Sedentary', '1-2 days/week', '3-4 days/week', '5+ days/week'],
                        'required' => true,
                        'section' => 'Screening',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'screening_fall_risk',
                        'label' => 'Fall Risk (age 65+)',
                        'type' => 'radio',
                        'options' => ['Not applicable', 'Low risk', 'Moderate risk', 'High risk'],
                        'required' => false,
                        'section' => 'Screening',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    // Assessment & Plan
                    [
                        'id' => 'assessment',
                        'label' => 'Assessment',
                        'type' => 'textarea',
                        'options' => null,
                        'required' => true,
                        'section' => 'Assessment & Plan',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'plan',
                        'label' => 'Plan',
                        'type' => 'textarea',
                        'options' => null,
                        'required' => true,
                        'section' => 'Assessment & Plan',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'follow_up',
                        'label' => 'Follow-up',
                        'type' => 'select',
                        'options' => ['As needed', '1 week', '2 weeks', '1 month', '3 months', '6 months', '1 year'],
                        'required' => true,
                        'section' => 'Assessment & Plan',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                ],
            ],

            // ─── Acute Visit ───
            [
                'name' => 'Acute Visit',
                'description' => 'Template for acute/sick visits including chief complaint, HPI, vitals, exam findings, assessment, and plan.',
                'visit_type' => 'acute',
                'sort_order' => 2,
                'fields' => [
                    [
                        'id' => 'chief_complaint',
                        'label' => 'Chief Complaint',
                        'type' => 'text',
                        'options' => null,
                        'required' => true,
                        'section' => 'Chief Complaint',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    // HPI
                    [
                        'id' => 'hpi_onset',
                        'label' => 'Onset',
                        'type' => 'text',
                        'options' => null,
                        'required' => true,
                        'section' => 'History of Present Illness',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'hpi_location',
                        'label' => 'Location',
                        'type' => 'text',
                        'options' => null,
                        'required' => false,
                        'section' => 'History of Present Illness',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'hpi_duration',
                        'label' => 'Duration',
                        'type' => 'text',
                        'options' => null,
                        'required' => true,
                        'section' => 'History of Present Illness',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'hpi_severity',
                        'label' => 'Severity',
                        'type' => 'select',
                        'options' => ['Mild', 'Moderate', 'Severe'],
                        'required' => true,
                        'section' => 'History of Present Illness',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'hpi_quality',
                        'label' => 'Quality/Character',
                        'type' => 'text',
                        'options' => null,
                        'required' => false,
                        'section' => 'History of Present Illness',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'hpi_modifying_factors',
                        'label' => 'Modifying Factors',
                        'type' => 'textarea',
                        'options' => null,
                        'required' => false,
                        'section' => 'History of Present Illness',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'hpi_associated_symptoms',
                        'label' => 'Associated Symptoms',
                        'type' => 'textarea',
                        'options' => null,
                        'required' => false,
                        'section' => 'History of Present Illness',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    // Vitals
                    [
                        'id' => 'vitals_bp_systolic',
                        'label' => 'Blood Pressure (Systolic)',
                        'type' => 'number',
                        'options' => null,
                        'required' => true,
                        'section' => 'Vitals',
                        'unit' => 'mmHg',
                        'reference_range' => ['min' => 90, 'max' => 120],
                    ],
                    [
                        'id' => 'vitals_bp_diastolic',
                        'label' => 'Blood Pressure (Diastolic)',
                        'type' => 'number',
                        'options' => null,
                        'required' => true,
                        'section' => 'Vitals',
                        'unit' => 'mmHg',
                        'reference_range' => ['min' => 60, 'max' => 80],
                    ],
                    [
                        'id' => 'vitals_heart_rate',
                        'label' => 'Heart Rate',
                        'type' => 'number',
                        'options' => null,
                        'required' => true,
                        'section' => 'Vitals',
                        'unit' => 'bpm',
                        'reference_range' => ['min' => 60, 'max' => 100],
                    ],
                    [
                        'id' => 'vitals_temperature',
                        'label' => 'Temperature',
                        'type' => 'number',
                        'options' => null,
                        'required' => true,
                        'section' => 'Vitals',
                        'unit' => '°F',
                        'reference_range' => ['min' => 97.0, 'max' => 99.0],
                    ],
                    [
                        'id' => 'vitals_o2_sat',
                        'label' => 'O2 Saturation',
                        'type' => 'number',
                        'options' => null,
                        'required' => true,
                        'section' => 'Vitals',
                        'unit' => '%',
                        'reference_range' => ['min' => 95, 'max' => 100],
                    ],
                    // Exam Findings
                    [
                        'id' => 'exam_general',
                        'label' => 'General Appearance',
                        'type' => 'text',
                        'options' => null,
                        'required' => true,
                        'section' => 'Exam Findings',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'exam_findings',
                        'label' => 'Pertinent Exam Findings',
                        'type' => 'textarea',
                        'options' => null,
                        'required' => true,
                        'section' => 'Exam Findings',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    // Assessment & Plan
                    [
                        'id' => 'assessment',
                        'label' => 'Assessment',
                        'type' => 'textarea',
                        'options' => null,
                        'required' => true,
                        'section' => 'Assessment & Plan',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'plan',
                        'label' => 'Plan',
                        'type' => 'textarea',
                        'options' => null,
                        'required' => true,
                        'section' => 'Assessment & Plan',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'return_precautions',
                        'label' => 'Return Precautions',
                        'type' => 'textarea',
                        'options' => null,
                        'required' => false,
                        'section' => 'Assessment & Plan',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'follow_up',
                        'label' => 'Follow-up',
                        'type' => 'select',
                        'options' => ['As needed', '24-48 hours', '1 week', '2 weeks', '1 month'],
                        'required' => true,
                        'section' => 'Assessment & Plan',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                ],
            ],

            // ─── Chronic Disease Follow-up ───
            [
                'name' => 'Chronic Disease Follow-up',
                'description' => 'Template for chronic disease management follow-up visits with condition-specific metrics, medication review, vitals, goals, and plan.',
                'visit_type' => 'chronic',
                'sort_order' => 3,
                'fields' => [
                    [
                        'id' => 'primary_condition',
                        'label' => 'Primary Condition',
                        'type' => 'select',
                        'options' => ['Hypertension', 'Type 2 Diabetes', 'Hyperlipidemia', 'Asthma/COPD', 'Heart Failure', 'Chronic Kidney Disease', 'Thyroid Disorder', 'Other'],
                        'required' => true,
                        'section' => 'Condition',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'condition_other',
                        'label' => 'Other Condition (specify)',
                        'type' => 'text',
                        'options' => null,
                        'required' => false,
                        'section' => 'Condition',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    // Condition-specific metrics
                    [
                        'id' => 'metric_hba1c',
                        'label' => 'HbA1c (if diabetic)',
                        'type' => 'number',
                        'options' => null,
                        'required' => false,
                        'section' => 'Condition Metrics',
                        'unit' => '%',
                        'reference_range' => ['min' => 4.0, 'max' => 7.0],
                    ],
                    [
                        'id' => 'metric_fasting_glucose',
                        'label' => 'Fasting Glucose',
                        'type' => 'number',
                        'options' => null,
                        'required' => false,
                        'section' => 'Condition Metrics',
                        'unit' => 'mg/dL',
                        'reference_range' => ['min' => 70, 'max' => 100],
                    ],
                    [
                        'id' => 'metric_ldl',
                        'label' => 'LDL Cholesterol',
                        'type' => 'number',
                        'options' => null,
                        'required' => false,
                        'section' => 'Condition Metrics',
                        'unit' => 'mg/dL',
                        'reference_range' => ['min' => 0, 'max' => 100],
                    ],
                    [
                        'id' => 'metric_egfr',
                        'label' => 'eGFR (if CKD)',
                        'type' => 'number',
                        'options' => null,
                        'required' => false,
                        'section' => 'Condition Metrics',
                        'unit' => 'mL/min',
                        'reference_range' => ['min' => 60, 'max' => 120],
                    ],
                    // Medication Review
                    [
                        'id' => 'current_medications',
                        'label' => 'Current Medications',
                        'type' => 'textarea',
                        'options' => null,
                        'required' => true,
                        'section' => 'Medication Review',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'medication_adherence',
                        'label' => 'Medication Adherence',
                        'type' => 'select',
                        'options' => ['Excellent (>90%)', 'Good (75-90%)', 'Fair (50-75%)', 'Poor (<50%)'],
                        'required' => true,
                        'section' => 'Medication Review',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'medication_side_effects',
                        'label' => 'Side Effects',
                        'type' => 'textarea',
                        'options' => null,
                        'required' => false,
                        'section' => 'Medication Review',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'medication_changes',
                        'label' => 'Medication Changes',
                        'type' => 'textarea',
                        'options' => null,
                        'required' => false,
                        'section' => 'Medication Review',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    // Vitals
                    [
                        'id' => 'vitals_bp_systolic',
                        'label' => 'Blood Pressure (Systolic)',
                        'type' => 'number',
                        'options' => null,
                        'required' => true,
                        'section' => 'Vitals',
                        'unit' => 'mmHg',
                        'reference_range' => ['min' => 90, 'max' => 120],
                    ],
                    [
                        'id' => 'vitals_bp_diastolic',
                        'label' => 'Blood Pressure (Diastolic)',
                        'type' => 'number',
                        'options' => null,
                        'required' => true,
                        'section' => 'Vitals',
                        'unit' => 'mmHg',
                        'reference_range' => ['min' => 60, 'max' => 80],
                    ],
                    [
                        'id' => 'vitals_heart_rate',
                        'label' => 'Heart Rate',
                        'type' => 'number',
                        'options' => null,
                        'required' => true,
                        'section' => 'Vitals',
                        'unit' => 'bpm',
                        'reference_range' => ['min' => 60, 'max' => 100],
                    ],
                    [
                        'id' => 'vitals_weight',
                        'label' => 'Weight',
                        'type' => 'number',
                        'options' => null,
                        'required' => true,
                        'section' => 'Vitals',
                        'unit' => 'lbs',
                        'reference_range' => null,
                    ],
                    // Goals
                    [
                        'id' => 'patient_goals',
                        'label' => 'Patient Goals',
                        'type' => 'textarea',
                        'options' => null,
                        'required' => true,
                        'section' => 'Goals & Plan',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'goal_progress',
                        'label' => 'Goal Progress',
                        'type' => 'select',
                        'options' => ['Meeting goals', 'Partial progress', 'Not meeting goals', 'Goals need revision'],
                        'required' => true,
                        'section' => 'Goals & Plan',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'plan',
                        'label' => 'Plan',
                        'type' => 'textarea',
                        'options' => null,
                        'required' => true,
                        'section' => 'Goals & Plan',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'follow_up',
                        'label' => 'Follow-up',
                        'type' => 'select',
                        'options' => ['1 month', '2 months', '3 months', '6 months'],
                        'required' => true,
                        'section' => 'Goals & Plan',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                ],
            ],

            // ─── Procedure Note ───
            [
                'name' => 'Procedure Note',
                'description' => 'Template for documenting in-office procedures including procedure name, indication, consent, technique, findings, complications, and follow-up.',
                'visit_type' => 'procedure',
                'sort_order' => 4,
                'fields' => [
                    [
                        'id' => 'procedure_name',
                        'label' => 'Procedure Name',
                        'type' => 'text',
                        'options' => null,
                        'required' => true,
                        'section' => 'Procedure',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'procedure_date',
                        'label' => 'Procedure Date',
                        'type' => 'date',
                        'options' => null,
                        'required' => true,
                        'section' => 'Procedure',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'indication',
                        'label' => 'Indication',
                        'type' => 'textarea',
                        'options' => null,
                        'required' => true,
                        'section' => 'Procedure',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'consent_obtained',
                        'label' => 'Informed Consent Obtained',
                        'type' => 'checkbox',
                        'options' => null,
                        'required' => true,
                        'section' => 'Consent',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'consent_details',
                        'label' => 'Consent Details',
                        'type' => 'textarea',
                        'options' => null,
                        'required' => false,
                        'section' => 'Consent',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'anesthesia',
                        'label' => 'Anesthesia/Analgesia',
                        'type' => 'select',
                        'options' => ['None', 'Local anesthesia', 'Topical anesthesia', 'Conscious sedation', 'Other'],
                        'required' => true,
                        'section' => 'Technique',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'technique',
                        'label' => 'Technique / Description',
                        'type' => 'textarea',
                        'options' => null,
                        'required' => true,
                        'section' => 'Technique',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'specimens',
                        'label' => 'Specimens Collected',
                        'type' => 'textarea',
                        'options' => null,
                        'required' => false,
                        'section' => 'Technique',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'findings',
                        'label' => 'Findings',
                        'type' => 'textarea',
                        'options' => null,
                        'required' => true,
                        'section' => 'Findings',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'complications',
                        'label' => 'Complications',
                        'type' => 'select',
                        'options' => ['None', 'Minor bleeding', 'Infection', 'Pain', 'Allergic reaction', 'Other'],
                        'required' => true,
                        'section' => 'Findings',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'complication_details',
                        'label' => 'Complication Details',
                        'type' => 'textarea',
                        'options' => null,
                        'required' => false,
                        'section' => 'Findings',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'patient_tolerance',
                        'label' => 'Patient Tolerance',
                        'type' => 'select',
                        'options' => ['Tolerated well', 'Tolerated with mild discomfort', 'Significant discomfort', 'Poor tolerance'],
                        'required' => true,
                        'section' => 'Findings',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'post_procedure_instructions',
                        'label' => 'Post-Procedure Instructions',
                        'type' => 'textarea',
                        'options' => null,
                        'required' => true,
                        'section' => 'Follow-up',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                    [
                        'id' => 'follow_up',
                        'label' => 'Follow-up',
                        'type' => 'select',
                        'options' => ['24-48 hours', '1 week', '2 weeks', '1 month', 'As needed'],
                        'required' => true,
                        'section' => 'Follow-up',
                        'unit' => null,
                        'reference_range' => null,
                    ],
                ],
            ],
        ];

        foreach ($templates as $template) {
            try {
                $existing = ChartTemplate::where('name', $template['name'])
                    ->whereNull('tenant_id')
                    ->where('is_system', true)
                    ->first();

                $data = [
                    'name' => $template['name'],
                    'description' => $template['description'],
                    'visit_type' => $template['visit_type'],
                    'fields' => $template['fields'],
                    'is_active' => true,
                    'is_system' => true,
                    'sort_order' => $template['sort_order'],
                ];

                if ($existing) {
                    $existing->update($data);
                } else {
                    ChartTemplate::create(array_merge($data, [
                        'tenant_id' => null,
                    ]));
                }

                $seeded++;
            } catch (\Throwable $e) {
                $this->command->error("Failed to seed chart template [{$template['name']}]: " . $e->getMessage());
                Log::error('ChartTemplateSeeder failed', ['name' => $template['name'], 'error' => $e->getMessage()]);
            }
        }

        $this->command->info("Seeded {$seeded} chart templates.");
    }
}
