<?php

namespace Database\Seeders;

use App\Models\MasterSpecialty;
use Illuminate\Database\Seeder;

class MasterSpecialtySeeder extends Seeder
{
    public function run(): void
    {
        $specialties = [
            // ─── Psychiatry ───
            [
                'name' => 'Psychiatry',
                'code' => 'psychiatry',
                'description' => 'Mental health evaluation, medication management, psychotherapy, and crisis intervention.',
                'default_screening_tools' => ['phq9', 'gad7', 'asrs', 'audit_c', 'pcl5', 'mdq', 'cssrs'],
                'default_appointment_types' => [
                    ['name' => 'Initial Psychiatric Evaluation', 'duration_minutes' => 60, 'is_telehealth' => true],
                    ['name' => 'Medication Management', 'duration_minutes' => 30, 'is_telehealth' => true],
                    ['name' => 'Therapy Session', 'duration_minutes' => 50, 'is_telehealth' => true],
                    ['name' => 'Crisis Assessment', 'duration_minutes' => 15, 'is_telehealth' => true],
                    ['name' => 'Follow-Up', 'duration_minutes' => 30, 'is_telehealth' => true],
                    ['name' => 'Psychological Testing', 'duration_minutes' => 90, 'is_telehealth' => false],
                ],
                'default_diagnosis_favorites' => [
                    ['code' => 'F32.1', 'description' => 'Major depressive disorder, single episode, moderate'],
                    ['code' => 'F32.0', 'description' => 'Major depressive disorder, single episode, mild'],
                    ['code' => 'F33.1', 'description' => 'Major depressive disorder, recurrent, moderate'],
                    ['code' => 'F41.1', 'description' => 'Generalized anxiety disorder'],
                    ['code' => 'F41.0', 'description' => 'Panic disorder'],
                    ['code' => 'F43.10', 'description' => 'Post-traumatic stress disorder, unspecified'],
                    ['code' => 'F90.0', 'description' => 'ADHD, predominantly inattentive type'],
                    ['code' => 'F90.1', 'description' => 'ADHD, predominantly hyperactive type'],
                    ['code' => 'F90.2', 'description' => 'ADHD, combined type'],
                    ['code' => 'F31.9', 'description' => 'Bipolar disorder, unspecified'],
                    ['code' => 'F42.2', 'description' => 'Obsessive-compulsive disorder, mixed'],
                    ['code' => 'F10.20', 'description' => 'Alcohol use disorder, moderate'],
                    ['code' => 'F50.00', 'description' => 'Anorexia nervosa, unspecified'],
                    ['code' => 'F51.01', 'description' => 'Primary insomnia'],
                    ['code' => 'F60.3', 'description' => 'Borderline personality disorder'],
                ],
                'default_medication_categories' => [
                    'SSRIs', 'SNRIs', 'Atypical Antidepressants', 'Tricyclics', 'MAOIs',
                    'Benzodiazepines', 'Buspirone', 'Mood Stabilizers', 'Atypical Antipsychotics',
                    'Stimulants', 'Non-Stimulant ADHD', 'Sleep Aids', 'Anti-Anxiety',
                ],
                'default_lab_panels' => [
                    'CBC', 'CMP', 'TSH', 'Lipid Panel', 'HbA1c', 'Lithium Level',
                    'Valproic Acid Level', 'Urine Drug Screen', 'Prolactin',
                    'Metabolic Panel for Antipsychotics',
                ],
                'default_plan_templates' => [
                    [
                        'name' => 'Essential',
                        'monthly_price' => 99.00,
                        'annual_price' => 999.00,
                        'visits_per_month' => 1,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 24,
                        'crisis_support' => false,
                        'badge_text' => null,
                    ],
                    [
                        'name' => 'Complete',
                        'monthly_price' => 199.00,
                        'annual_price' => 1999.00,
                        'visits_per_month' => 2,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 4,
                        'crisis_support' => true,
                        'badge_text' => 'Most Popular',
                    ],
                    [
                        'name' => 'Premium',
                        'monthly_price' => 299.00,
                        'annual_price' => 2999.00,
                        'visits_per_month' => -1,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 1,
                        'crisis_support' => true,
                        'badge_text' => 'Best Value',
                    ],
                ],
                'default_intake_sections' => [
                    'demographics', 'psychiatric_history', 'substance_use',
                    'family_psychiatric_history', 'medications', 'allergies',
                    'medical_history', 'insurance', 'emergency_contacts', 'consent',
                ],
                'default_addons' => [
                    ['name' => 'Genetic Testing', 'price' => 150.00, 'billing_type' => 'one_time'],
                    ['name' => 'Extended Session (90 min)', 'price' => 75.00, 'billing_type' => 'one_time'],
                    ['name' => 'Letter/Form Completion', 'price' => 25.00, 'billing_type' => 'one_time'],
                    ['name' => 'FMLA Paperwork', 'price' => 50.00, 'billing_type' => 'one_time'],
                    ['name' => 'Weekly Therapy Add-On', 'price' => 200.00, 'billing_type' => 'recurring'],
                ],
            ],

            // ─── Primary Care ───
            [
                'name' => 'Primary Care',
                'code' => 'primary_care',
                'description' => 'Comprehensive primary care including preventive services, chronic disease management, and acute care.',
                'default_screening_tools' => ['phq9', 'gad7'],
                'default_appointment_types' => [
                    ['name' => 'New Patient Visit', 'duration_minutes' => 60, 'is_telehealth' => false],
                    ['name' => 'Follow-Up', 'duration_minutes' => 30, 'is_telehealth' => false],
                    ['name' => 'Wellness Exam', 'duration_minutes' => 45, 'is_telehealth' => true],
                    ['name' => 'Urgent Visit', 'duration_minutes' => 20, 'is_telehealth' => true],
                    ['name' => 'Chronic Care Management', 'duration_minutes' => 30, 'is_telehealth' => true],
                    ['name' => 'Procedure Visit', 'duration_minutes' => 30, 'is_telehealth' => false],
                ],
                'default_diagnosis_favorites' => [
                    ['code' => 'I10', 'description' => 'Essential (primary) hypertension'],
                    ['code' => 'E11.9', 'description' => 'Type 2 diabetes mellitus without complications'],
                    ['code' => 'E78.5', 'description' => 'Hyperlipidemia, unspecified'],
                    ['code' => 'J06.9', 'description' => 'Acute upper respiratory infection, unspecified'],
                    ['code' => 'M54.5', 'description' => 'Low back pain'],
                    ['code' => 'E03.9', 'description' => 'Hypothyroidism, unspecified'],
                    ['code' => 'J45.20', 'description' => 'Mild intermittent asthma, uncomplicated'],
                    ['code' => 'K21.0', 'description' => 'Gastro-esophageal reflux disease with esophagitis'],
                    ['code' => 'N39.0', 'description' => 'Urinary tract infection, site not specified'],
                    ['code' => 'E66.01', 'description' => 'Morbid (severe) obesity due to excess calories'],
                ],
                'default_medication_categories' => [
                    'Antihypertensives', 'Statins', 'Metformin/Diabetes', 'Antibiotics',
                    'NSAIDs', 'PPIs', 'Thyroid', 'Inhalers', 'Antihistamines',
                ],
                'default_lab_panels' => [
                    'CBC', 'CMP', 'Lipid Panel', 'HbA1c', 'TSH',
                    'Urinalysis', 'PSA', 'Vitamin D', 'Iron Studies', 'Hepatic Panel',
                ],
                'default_plan_templates' => [
                    [
                        'name' => 'Basic',
                        'monthly_price' => 79.00,
                        'annual_price' => 799.00,
                        'visits_per_month' => 1,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 24,
                        'crisis_support' => false,
                        'badge_text' => null,
                    ],
                    [
                        'name' => 'Standard',
                        'monthly_price' => 149.00,
                        'annual_price' => 1499.00,
                        'visits_per_month' => 2,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 12,
                        'crisis_support' => false,
                        'badge_text' => 'Most Popular',
                    ],
                    [
                        'name' => 'Premium',
                        'monthly_price' => 249.00,
                        'annual_price' => 2499.00,
                        'visits_per_month' => -1,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 4,
                        'crisis_support' => false,
                        'badge_text' => 'Best Value',
                    ],
                ],
                'default_intake_sections' => [
                    'demographics', 'medical_history', 'surgical_history',
                    'family_history', 'social_history', 'medications', 'allergies',
                    'immunizations', 'insurance', 'emergency_contacts', 'consent',
                ],
                'default_addons' => [
                    ['name' => 'Annual Wellness Exam', 'price' => 0.00, 'billing_type' => 'one_time'],
                    ['name' => 'Sports Physical', 'price' => 50.00, 'billing_type' => 'one_time'],
                    ['name' => 'Travel Consultation', 'price' => 75.00, 'billing_type' => 'one_time'],
                ],
            ],

            // ─── Family Medicine ───
            [
                'name' => 'Family Medicine',
                'code' => 'family_medicine',
                'description' => 'Comprehensive family medicine for patients of all ages, including preventive care and chronic disease management.',
                'default_screening_tools' => ['phq9', 'gad7'],
                'default_appointment_types' => [
                    ['name' => 'New Patient Visit', 'duration_minutes' => 60, 'is_telehealth' => false],
                    ['name' => 'Follow-Up', 'duration_minutes' => 30, 'is_telehealth' => false],
                    ['name' => 'Wellness Exam', 'duration_minutes' => 45, 'is_telehealth' => true],
                    ['name' => 'Urgent Visit', 'duration_minutes' => 20, 'is_telehealth' => true],
                    ['name' => 'Chronic Care Management', 'duration_minutes' => 30, 'is_telehealth' => true],
                    ['name' => 'Procedure Visit', 'duration_minutes' => 30, 'is_telehealth' => false],
                ],
                'default_diagnosis_favorites' => [
                    ['code' => 'I10', 'description' => 'Essential (primary) hypertension'],
                    ['code' => 'E11.9', 'description' => 'Type 2 diabetes mellitus without complications'],
                    ['code' => 'E78.5', 'description' => 'Hyperlipidemia, unspecified'],
                    ['code' => 'J06.9', 'description' => 'Acute upper respiratory infection, unspecified'],
                    ['code' => 'M54.5', 'description' => 'Low back pain'],
                    ['code' => 'E03.9', 'description' => 'Hypothyroidism, unspecified'],
                    ['code' => 'J45.20', 'description' => 'Mild intermittent asthma, uncomplicated'],
                    ['code' => 'K21.0', 'description' => 'Gastro-esophageal reflux disease with esophagitis'],
                    ['code' => 'N39.0', 'description' => 'Urinary tract infection, site not specified'],
                    ['code' => 'E66.01', 'description' => 'Morbid (severe) obesity due to excess calories'],
                ],
                'default_medication_categories' => [
                    'Antihypertensives', 'Statins', 'Metformin/Diabetes', 'Antibiotics',
                    'NSAIDs', 'PPIs', 'Thyroid', 'Inhalers', 'Antihistamines',
                ],
                'default_lab_panels' => [
                    'CBC', 'CMP', 'Lipid Panel', 'HbA1c', 'TSH',
                    'Urinalysis', 'PSA', 'Vitamin D', 'Iron Studies', 'Hepatic Panel',
                ],
                'default_plan_templates' => [
                    [
                        'name' => 'Basic',
                        'monthly_price' => 79.00,
                        'annual_price' => 799.00,
                        'visits_per_month' => 1,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 24,
                        'crisis_support' => false,
                        'badge_text' => null,
                    ],
                    [
                        'name' => 'Standard',
                        'monthly_price' => 149.00,
                        'annual_price' => 1499.00,
                        'visits_per_month' => 2,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 12,
                        'crisis_support' => false,
                        'badge_text' => 'Most Popular',
                    ],
                    [
                        'name' => 'Premium',
                        'monthly_price' => 249.00,
                        'annual_price' => 2499.00,
                        'visits_per_month' => -1,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 4,
                        'crisis_support' => false,
                        'badge_text' => 'Best Value',
                    ],
                ],
                'default_intake_sections' => [
                    'demographics', 'medical_history', 'surgical_history',
                    'family_history', 'social_history', 'medications', 'allergies',
                    'immunizations', 'insurance', 'emergency_contacts', 'consent',
                ],
                'default_addons' => [
                    ['name' => 'Annual Wellness Exam', 'price' => 0.00, 'billing_type' => 'one_time'],
                    ['name' => 'Sports Physical', 'price' => 50.00, 'billing_type' => 'one_time'],
                    ['name' => 'Travel Consultation', 'price' => 75.00, 'billing_type' => 'one_time'],
                ],
            ],

            // ─── Pediatrics ───
            [
                'name' => 'Pediatrics',
                'code' => 'pediatrics',
                'description' => 'Comprehensive pediatric care including well-child visits, developmental screening, and immunizations.',
                'default_screening_tools' => [],
                'default_appointment_types' => [
                    ['name' => 'Well-Child Visit', 'duration_minutes' => 45, 'is_telehealth' => false],
                    ['name' => 'Sick Visit', 'duration_minutes' => 20, 'is_telehealth' => true],
                    ['name' => 'Developmental Screening', 'duration_minutes' => 45, 'is_telehealth' => false],
                    ['name' => 'Behavioral Assessment', 'duration_minutes' => 60, 'is_telehealth' => false],
                    ['name' => 'Immunization Visit', 'duration_minutes' => 15, 'is_telehealth' => false],
                ],
                'default_diagnosis_favorites' => [
                    ['code' => 'J06.9', 'description' => 'Acute upper respiratory infection, unspecified'],
                    ['code' => 'J20.9', 'description' => 'Acute bronchitis, unspecified'],
                    ['code' => 'H66.90', 'description' => 'Otitis media, unspecified, unspecified ear'],
                    ['code' => 'B34.9', 'description' => 'Viral infection, unspecified'],
                    ['code' => 'R50.9', 'description' => 'Fever, unspecified'],
                    ['code' => 'J02.9', 'description' => 'Acute pharyngitis, unspecified'],
                    ['code' => 'L20.9', 'description' => 'Atopic dermatitis, unspecified'],
                    ['code' => 'R63.0', 'description' => 'Anorexia (failure to thrive)'],
                    ['code' => 'F90.9', 'description' => 'ADHD, unspecified type'],
                    ['code' => 'Z00.129', 'description' => 'Encounter for routine child health examination without abnormal findings'],
                ],
                'default_medication_categories' => [
                    'Antibiotics', 'Antipyretics', 'Antihistamines', 'Inhalers',
                    'Topical Steroids', 'Probiotics',
                ],
                'default_lab_panels' => [
                    'CBC', 'Lead Level', 'Iron Studies', 'Urinalysis',
                    'Strep Test', 'Flu Test',
                ],
                'default_plan_templates' => [
                    [
                        'name' => 'Family Pediatrics',
                        'monthly_price' => 89.00,
                        'annual_price' => 899.00,
                        'visits_per_month' => 1,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 12,
                        'crisis_support' => false,
                        'badge_text' => null,
                    ],
                    [
                        'name' => 'Complete Pediatrics',
                        'monthly_price' => 159.00,
                        'annual_price' => 1599.00,
                        'visits_per_month' => 2,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 4,
                        'crisis_support' => false,
                        'badge_text' => 'Most Popular',
                    ],
                ],
                'default_intake_sections' => [
                    'demographics', 'birth_history', 'developmental_history',
                    'immunizations', 'family_history', 'medications', 'allergies',
                    'insurance', 'emergency_contacts', 'consent',
                ],
                'default_addons' => [
                    ['name' => 'Well-Child Visit (included)', 'price' => 0.00, 'billing_type' => 'one_time'],
                    ['name' => 'School Physical', 'price' => 40.00, 'billing_type' => 'one_time'],
                    ['name' => 'Camp Physical', 'price' => 40.00, 'billing_type' => 'one_time'],
                ],
            ],

            // ─── Dermatology ───
            [
                'name' => 'Dermatology',
                'code' => 'dermatology',
                'description' => 'Medical and cosmetic dermatology including skin cancer screening, acne treatment, and procedures.',
                'default_screening_tools' => [],
                'default_appointment_types' => [
                    ['name' => 'New Patient Consultation', 'duration_minutes' => 30, 'is_telehealth' => false],
                    ['name' => 'Follow-Up', 'duration_minutes' => 20, 'is_telehealth' => false],
                    ['name' => 'Cosmetic Consultation', 'duration_minutes' => 30, 'is_telehealth' => false],
                    ['name' => 'Procedure', 'duration_minutes' => 45, 'is_telehealth' => false],
                    ['name' => 'Skin Check', 'duration_minutes' => 30, 'is_telehealth' => true],
                    ['name' => 'Photo Review', 'duration_minutes' => 15, 'is_telehealth' => true],
                ],
                'default_diagnosis_favorites' => [
                    ['code' => 'L70.0', 'description' => 'Acne vulgaris'],
                    ['code' => 'L40.0', 'description' => 'Psoriasis vulgaris'],
                    ['code' => 'L30.9', 'description' => 'Dermatitis, unspecified'],
                    ['code' => 'L82.1', 'description' => 'Other seborrheic keratosis'],
                    ['code' => 'D22.9', 'description' => 'Melanocytic nevi, unspecified'],
                    ['code' => 'C44.91', 'description' => 'Basal cell carcinoma of skin, unspecified'],
                    ['code' => 'L50.9', 'description' => 'Urticaria, unspecified'],
                    ['code' => 'B35.1', 'description' => 'Tinea unguium'],
                ],
                'default_medication_categories' => [
                    'Topical Retinoids', 'Topical Steroids', 'Topical Antibiotics',
                    'Oral Antibiotics', 'Biologics', 'Antifungals', 'Immunomodulators',
                ],
                'default_lab_panels' => [
                    'CBC', 'CMP', 'ANA', 'Skin Biopsy', 'Fungal Culture',
                ],
                'default_plan_templates' => [
                    [
                        'name' => 'Skin Care',
                        'monthly_price' => 99.00,
                        'annual_price' => 999.00,
                        'visits_per_month' => 1,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 24,
                        'crisis_support' => false,
                        'badge_text' => null,
                    ],
                    [
                        'name' => 'Comprehensive',
                        'monthly_price' => 179.00,
                        'annual_price' => 1799.00,
                        'visits_per_month' => 2,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 12,
                        'crisis_support' => false,
                        'badge_text' => 'Most Popular',
                    ],
                ],
                'default_intake_sections' => [
                    'demographics', 'medical_history', 'skin_history',
                    'medications', 'allergies', 'insurance', 'emergency_contacts', 'consent',
                ],
                'default_addons' => [
                    ['name' => 'Cosmetic Consultation', 'price' => 100.00, 'billing_type' => 'one_time'],
                    ['name' => 'Chemical Peel', 'price' => 150.00, 'billing_type' => 'one_time'],
                    ['name' => 'Mole Mapping', 'price' => 200.00, 'billing_type' => 'one_time'],
                ],
            ],

            // ─── Cardiology ───
            [
                'name' => 'Cardiology',
                'code' => 'cardiology',
                'description' => 'Cardiovascular evaluation, management of heart disease, hypertension, and remote cardiac monitoring.',
                'default_screening_tools' => [],
                'default_appointment_types' => [
                    ['name' => 'New Patient Evaluation', 'duration_minutes' => 60, 'is_telehealth' => false],
                    ['name' => 'Follow-Up', 'duration_minutes' => 30, 'is_telehealth' => false],
                    ['name' => 'ECG Review', 'duration_minutes' => 15, 'is_telehealth' => true],
                    ['name' => 'Stress Test Review', 'duration_minutes' => 30, 'is_telehealth' => false],
                    ['name' => 'Remote Monitoring Review', 'duration_minutes' => 20, 'is_telehealth' => true],
                ],
                'default_diagnosis_favorites' => [
                    ['code' => 'I10', 'description' => 'Essential (primary) hypertension'],
                    ['code' => 'I25.10', 'description' => 'Atherosclerotic heart disease of native coronary artery without angina pectoris'],
                    ['code' => 'I48.91', 'description' => 'Unspecified atrial fibrillation'],
                    ['code' => 'I50.9', 'description' => 'Heart failure, unspecified'],
                    ['code' => 'I42.9', 'description' => 'Cardiomyopathy, unspecified'],
                    ['code' => 'R00.0', 'description' => 'Tachycardia, unspecified'],
                    ['code' => 'I73.9', 'description' => 'Peripheral vascular disease, unspecified'],
                    ['code' => 'E78.5', 'description' => 'Hyperlipidemia, unspecified'],
                ],
                'default_medication_categories' => [
                    'ACE Inhibitors', 'ARBs', 'Beta Blockers', 'Calcium Channel Blockers',
                    'Diuretics', 'Anticoagulants', 'Antiplatelets', 'Statins',
                    'Antiarrhythmics', 'Nitrates',
                ],
                'default_lab_panels' => [
                    'CBC', 'CMP', 'Lipid Panel', 'BNP/NT-proBNP', 'Troponin',
                    'INR/PT', 'TSH', 'HbA1c', 'Magnesium', 'D-Dimer',
                ],
                'default_plan_templates' => [
                    [
                        'name' => 'Heart Health',
                        'monthly_price' => 129.00,
                        'annual_price' => 1299.00,
                        'visits_per_month' => 1,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 24,
                        'crisis_support' => false,
                        'badge_text' => null,
                    ],
                    [
                        'name' => 'Cardiac Care',
                        'monthly_price' => 229.00,
                        'annual_price' => 2299.00,
                        'visits_per_month' => 2,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 4,
                        'crisis_support' => true,
                        'badge_text' => 'Most Popular',
                    ],
                ],
                'default_intake_sections' => [
                    'demographics', 'cardiac_history', 'medical_history',
                    'surgical_history', 'family_history', 'medications', 'allergies',
                    'insurance', 'emergency_contacts', 'consent',
                ],
                'default_addons' => [
                    ['name' => 'Remote Cardiac Monitoring (monthly)', 'price' => 75.00, 'billing_type' => 'recurring'],
                    ['name' => 'ECG Interpretation', 'price' => 25.00, 'billing_type' => 'one_time'],
                    ['name' => 'Cardiac Risk Assessment', 'price' => 100.00, 'billing_type' => 'one_time'],
                ],
            ],

            // ─── Internal Medicine ───
            [
                'name' => 'Internal Medicine',
                'code' => 'internal_medicine',
                'description' => 'Adult medicine focusing on prevention, diagnosis, and treatment of complex medical conditions.',
                'default_screening_tools' => ['phq9'],
                'default_appointment_types' => [
                    ['name' => 'New Patient Visit', 'duration_minutes' => 60, 'is_telehealth' => false],
                    ['name' => 'Follow-Up', 'duration_minutes' => 30, 'is_telehealth' => true],
                    ['name' => 'Annual Wellness Exam', 'duration_minutes' => 45, 'is_telehealth' => false],
                    ['name' => 'Urgent Visit', 'duration_minutes' => 20, 'is_telehealth' => true],
                    ['name' => 'Chronic Care Management', 'duration_minutes' => 30, 'is_telehealth' => true],
                ],
                'default_diagnosis_favorites' => [
                    ['code' => 'I10', 'description' => 'Essential (primary) hypertension'],
                    ['code' => 'E11.9', 'description' => 'Type 2 diabetes mellitus without complications'],
                    ['code' => 'E78.5', 'description' => 'Hyperlipidemia, unspecified'],
                    ['code' => 'E03.9', 'description' => 'Hypothyroidism, unspecified'],
                    ['code' => 'K21.0', 'description' => 'Gastro-esophageal reflux disease with esophagitis'],
                    ['code' => 'M54.5', 'description' => 'Low back pain'],
                    ['code' => 'J06.9', 'description' => 'Acute upper respiratory infection, unspecified'],
                    ['code' => 'E66.01', 'description' => 'Morbid (severe) obesity due to excess calories'],
                ],
                'default_medication_categories' => [
                    'Antihypertensives', 'Statins', 'Metformin/Diabetes', 'Antibiotics',
                    'NSAIDs', 'PPIs', 'Thyroid', 'Anticoagulants',
                ],
                'default_lab_panels' => [
                    'CBC', 'CMP', 'Lipid Panel', 'HbA1c', 'TSH',
                    'Urinalysis', 'Vitamin D', 'Iron Studies', 'Hepatic Panel', 'ESR/CRP',
                ],
                'default_plan_templates' => [
                    [
                        'name' => 'Basic',
                        'monthly_price' => 89.00,
                        'annual_price' => 899.00,
                        'visits_per_month' => 1,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 24,
                        'crisis_support' => false,
                        'badge_text' => null,
                    ],
                    [
                        'name' => 'Standard',
                        'monthly_price' => 159.00,
                        'annual_price' => 1599.00,
                        'visits_per_month' => 2,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 12,
                        'crisis_support' => false,
                        'badge_text' => 'Most Popular',
                    ],
                    [
                        'name' => 'Premium',
                        'monthly_price' => 259.00,
                        'annual_price' => 2599.00,
                        'visits_per_month' => -1,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 4,
                        'crisis_support' => false,
                        'badge_text' => 'Best Value',
                    ],
                ],
                'default_intake_sections' => [
                    'demographics', 'medical_history', 'surgical_history',
                    'family_history', 'social_history', 'medications', 'allergies',
                    'immunizations', 'insurance', 'emergency_contacts', 'consent',
                ],
                'default_addons' => [
                    ['name' => 'Executive Health Screen', 'price' => 200.00, 'billing_type' => 'one_time'],
                    ['name' => 'Extended Visit (60 min)', 'price' => 50.00, 'billing_type' => 'one_time'],
                ],
            ],

            // ─── Endocrinology ───
            [
                'name' => 'Endocrinology',
                'code' => 'endocrinology',
                'description' => 'Hormone disorders, diabetes management, thyroid conditions, and metabolic diseases.',
                'default_screening_tools' => [],
                'default_appointment_types' => [
                    ['name' => 'New Patient Evaluation', 'duration_minutes' => 60, 'is_telehealth' => false],
                    ['name' => 'Follow-Up', 'duration_minutes' => 30, 'is_telehealth' => true],
                    ['name' => 'Diabetes Management', 'duration_minutes' => 30, 'is_telehealth' => true],
                    ['name' => 'Thyroid Consultation', 'duration_minutes' => 30, 'is_telehealth' => true],
                ],
                'default_diagnosis_favorites' => [
                    ['code' => 'E11.9', 'description' => 'Type 2 diabetes mellitus without complications'],
                    ['code' => 'E03.9', 'description' => 'Hypothyroidism, unspecified'],
                    ['code' => 'E05.90', 'description' => 'Thyrotoxicosis, unspecified'],
                    ['code' => 'E04.1', 'description' => 'Nontoxic single thyroid nodule'],
                    ['code' => 'E21.0', 'description' => 'Primary hyperparathyroidism'],
                    ['code' => 'E66.01', 'description' => 'Morbid (severe) obesity due to excess calories'],
                    ['code' => 'E29.1', 'description' => 'Testicular hypofunction'],
                    ['code' => 'E11.65', 'description' => 'Type 2 diabetes mellitus with hyperglycemia'],
                ],
                'default_medication_categories' => [
                    'Insulin', 'Metformin/Diabetes', 'GLP-1 Agonists', 'SGLT2 Inhibitors',
                    'Thyroid Replacement', 'Anti-Thyroid', 'Hormone Replacement',
                ],
                'default_lab_panels' => [
                    'HbA1c', 'Fasting Glucose', 'TSH', 'Free T4', 'Free T3',
                    'Thyroid Antibodies', 'Cortisol', 'Testosterone',
                    'Calcium/PTH', 'Lipid Panel',
                ],
                'default_plan_templates' => [
                    [
                        'name' => 'Metabolic Health',
                        'monthly_price' => 119.00,
                        'annual_price' => 1199.00,
                        'visits_per_month' => 1,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 24,
                        'crisis_support' => false,
                        'badge_text' => null,
                    ],
                    [
                        'name' => 'Comprehensive Endocrine',
                        'monthly_price' => 209.00,
                        'annual_price' => 2099.00,
                        'visits_per_month' => 2,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 8,
                        'crisis_support' => false,
                        'badge_text' => 'Most Popular',
                    ],
                ],
                'default_intake_sections' => [
                    'demographics', 'endocrine_history', 'medical_history',
                    'family_history', 'medications', 'allergies',
                    'insurance', 'emergency_contacts', 'consent',
                ],
                'default_addons' => [
                    ['name' => 'CGM Setup & Training', 'price' => 100.00, 'billing_type' => 'one_time'],
                    ['name' => 'Insulin Pump Management (monthly)', 'price' => 50.00, 'billing_type' => 'recurring'],
                ],
            ],

            // ─── OB/GYN ───
            [
                'name' => 'OB/GYN',
                'code' => 'obgyn',
                'description' => 'Obstetric and gynecological care including prenatal, reproductive health, and preventive services.',
                'default_screening_tools' => ['phq9'],
                'default_appointment_types' => [
                    ['name' => 'New Patient Visit', 'duration_minutes' => 60, 'is_telehealth' => false],
                    ['name' => 'Follow-Up', 'duration_minutes' => 30, 'is_telehealth' => true],
                    ['name' => 'Annual Well-Woman Exam', 'duration_minutes' => 45, 'is_telehealth' => false],
                    ['name' => 'Prenatal Visit', 'duration_minutes' => 30, 'is_telehealth' => false],
                    ['name' => 'Contraception Consult', 'duration_minutes' => 30, 'is_telehealth' => true],
                ],
                'default_diagnosis_favorites' => [
                    ['code' => 'Z34.90', 'description' => 'Encounter for supervision of normal pregnancy, unspecified trimester'],
                    ['code' => 'N92.0', 'description' => 'Excessive and frequent menstruation with regular cycle'],
                    ['code' => 'N94.6', 'description' => 'Dysmenorrhea, unspecified'],
                    ['code' => 'E28.2', 'description' => 'Polycystic ovarian syndrome'],
                    ['code' => 'N95.1', 'description' => 'Menopausal and female climacteric states'],
                    ['code' => 'Z30.09', 'description' => 'Encounter for other general counseling and advice on contraception'],
                    ['code' => 'N76.0', 'description' => 'Acute vaginitis'],
                    ['code' => 'Z01.419', 'description' => 'Encounter for gynecological examination without abnormal findings'],
                ],
                'default_medication_categories' => [
                    'Oral Contraceptives', 'Hormone Replacement', 'Prenatal Vitamins',
                    'Antibiotics', 'Antifungals', 'Progesterone', 'GnRH Agonists',
                ],
                'default_lab_panels' => [
                    'CBC', 'CMP', 'Pap Smear', 'STI Panel', 'Prenatal Panel',
                    'hCG', 'Progesterone', 'Estradiol', 'FSH/LH', 'Thyroid Panel',
                ],
                'default_plan_templates' => [
                    [
                        'name' => 'Women\'s Wellness',
                        'monthly_price' => 99.00,
                        'annual_price' => 999.00,
                        'visits_per_month' => 1,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 24,
                        'crisis_support' => false,
                        'badge_text' => null,
                    ],
                    [
                        'name' => 'Complete OB/GYN',
                        'monthly_price' => 189.00,
                        'annual_price' => 1899.00,
                        'visits_per_month' => 2,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 8,
                        'crisis_support' => false,
                        'badge_text' => 'Most Popular',
                    ],
                ],
                'default_intake_sections' => [
                    'demographics', 'gynecological_history', 'obstetric_history',
                    'medical_history', 'family_history', 'medications', 'allergies',
                    'insurance', 'emergency_contacts', 'consent',
                ],
                'default_addons' => [
                    ['name' => 'Annual Well-Woman Exam (included)', 'price' => 0.00, 'billing_type' => 'one_time'],
                    ['name' => 'Fertility Consultation', 'price' => 150.00, 'billing_type' => 'one_time'],
                ],
            ],

            // ─── Functional Medicine ───
            [
                'name' => 'Functional Medicine',
                'code' => 'functional_medicine',
                'description' => 'Root-cause approach to chronic conditions using comprehensive testing, nutrition, and lifestyle interventions.',
                'default_screening_tools' => [],
                'default_appointment_types' => [
                    ['name' => 'Initial Comprehensive Visit', 'duration_minutes' => 90, 'is_telehealth' => true],
                    ['name' => 'Follow-Up', 'duration_minutes' => 45, 'is_telehealth' => true],
                    ['name' => 'Lab Review', 'duration_minutes' => 30, 'is_telehealth' => true],
                    ['name' => 'Nutrition Consultation', 'duration_minutes' => 45, 'is_telehealth' => true],
                ],
                'default_diagnosis_favorites' => [
                    ['code' => 'E03.9', 'description' => 'Hypothyroidism, unspecified'],
                    ['code' => 'K58.9', 'description' => 'Irritable bowel syndrome without diarrhea'],
                    ['code' => 'R53.83', 'description' => 'Other fatigue'],
                    ['code' => 'E66.01', 'description' => 'Morbid (severe) obesity due to excess calories'],
                    ['code' => 'G43.909', 'description' => 'Migraine, unspecified'],
                    ['code' => 'M79.3', 'description' => 'Panniculitis, unspecified'],
                    ['code' => 'E55.9', 'description' => 'Vitamin D deficiency, unspecified'],
                    ['code' => 'D50.9', 'description' => 'Iron deficiency anemia, unspecified'],
                ],
                'default_medication_categories' => [
                    'Supplements', 'Hormone Replacement', 'Thyroid', 'Probiotics',
                    'Anti-Inflammatory', 'Adaptogens',
                ],
                'default_lab_panels' => [
                    'Comprehensive Metabolic Panel', 'Full Thyroid Panel', 'Vitamin D',
                    'B12/Folate', 'Iron Studies', 'Inflammatory Markers (CRP/ESR)',
                    'Food Sensitivity Panel', 'Cortisol (AM)', 'DHEA-S', 'Omega-3 Index',
                ],
                'default_plan_templates' => [
                    [
                        'name' => 'Functional Health',
                        'monthly_price' => 149.00,
                        'annual_price' => 1499.00,
                        'visits_per_month' => 1,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 24,
                        'crisis_support' => false,
                        'badge_text' => null,
                    ],
                    [
                        'name' => 'Optimize',
                        'monthly_price' => 279.00,
                        'annual_price' => 2799.00,
                        'visits_per_month' => 2,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 8,
                        'crisis_support' => false,
                        'badge_text' => 'Most Popular',
                    ],
                ],
                'default_intake_sections' => [
                    'demographics', 'health_timeline', 'medical_history',
                    'nutrition_history', 'lifestyle', 'medications', 'supplements',
                    'allergies', 'insurance', 'emergency_contacts', 'consent',
                ],
                'default_addons' => [
                    ['name' => 'Comprehensive Lab Panel', 'price' => 250.00, 'billing_type' => 'one_time'],
                    ['name' => 'Food Sensitivity Test', 'price' => 200.00, 'billing_type' => 'one_time'],
                    ['name' => 'Genetic Testing', 'price' => 300.00, 'billing_type' => 'one_time'],
                ],
            ],

            // ─── Concierge Medicine ───
            [
                'name' => 'Concierge Medicine',
                'code' => 'concierge_medicine',
                'description' => 'Premium primary care with enhanced access, longer appointments, and personalized wellness programs.',
                'default_screening_tools' => ['phq9', 'gad7'],
                'default_appointment_types' => [
                    ['name' => 'Comprehensive Initial Visit', 'duration_minutes' => 90, 'is_telehealth' => false],
                    ['name' => 'Follow-Up', 'duration_minutes' => 45, 'is_telehealth' => true],
                    ['name' => 'Executive Physical', 'duration_minutes' => 120, 'is_telehealth' => false],
                    ['name' => 'Same-Day Urgent', 'duration_minutes' => 30, 'is_telehealth' => true],
                    ['name' => 'Wellness Review', 'duration_minutes' => 45, 'is_telehealth' => true],
                ],
                'default_diagnosis_favorites' => [
                    ['code' => 'I10', 'description' => 'Essential (primary) hypertension'],
                    ['code' => 'E11.9', 'description' => 'Type 2 diabetes mellitus without complications'],
                    ['code' => 'E78.5', 'description' => 'Hyperlipidemia, unspecified'],
                    ['code' => 'Z00.00', 'description' => 'Encounter for general adult medical examination without abnormal findings'],
                    ['code' => 'E03.9', 'description' => 'Hypothyroidism, unspecified'],
                    ['code' => 'E66.01', 'description' => 'Morbid (severe) obesity due to excess calories'],
                    ['code' => 'R53.83', 'description' => 'Other fatigue'],
                    ['code' => 'G47.00', 'description' => 'Insomnia, unspecified'],
                ],
                'default_medication_categories' => [
                    'Antihypertensives', 'Statins', 'Metformin/Diabetes', 'Antibiotics',
                    'NSAIDs', 'PPIs', 'Thyroid', 'Supplements', 'Hormone Replacement',
                ],
                'default_lab_panels' => [
                    'CBC', 'CMP', 'Lipid Panel', 'HbA1c', 'TSH', 'Vitamin D',
                    'B12', 'Iron Studies', 'hsCRP', 'Homocysteine',
                    'Testosterone', 'DHEA-S', 'PSA',
                ],
                'default_plan_templates' => [
                    [
                        'name' => 'Concierge Essential',
                        'monthly_price' => 199.00,
                        'annual_price' => 1999.00,
                        'visits_per_month' => 2,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 4,
                        'crisis_support' => false,
                        'badge_text' => null,
                    ],
                    [
                        'name' => 'Concierge Premium',
                        'monthly_price' => 349.00,
                        'annual_price' => 3499.00,
                        'visits_per_month' => -1,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 1,
                        'crisis_support' => true,
                        'badge_text' => 'Most Popular',
                    ],
                ],
                'default_intake_sections' => [
                    'demographics', 'medical_history', 'surgical_history',
                    'family_history', 'social_history', 'lifestyle',
                    'medications', 'supplements', 'allergies',
                    'insurance', 'emergency_contacts', 'consent',
                ],
                'default_addons' => [
                    ['name' => 'Executive Physical', 'price' => 500.00, 'billing_type' => 'one_time'],
                    ['name' => 'Comprehensive Wellness Panel', 'price' => 300.00, 'billing_type' => 'one_time'],
                    ['name' => 'Health Coaching (monthly)', 'price' => 100.00, 'billing_type' => 'recurring'],
                ],
            ],

            // ─── Pain Management ───
            [
                'name' => 'Pain Management',
                'code' => 'pain_management',
                'description' => 'Comprehensive pain evaluation and multimodal treatment including interventional procedures.',
                'default_screening_tools' => ['phq9'],
                'default_appointment_types' => [
                    ['name' => 'New Patient Evaluation', 'duration_minutes' => 60, 'is_telehealth' => false],
                    ['name' => 'Follow-Up', 'duration_minutes' => 30, 'is_telehealth' => true],
                    ['name' => 'Procedure Visit', 'duration_minutes' => 45, 'is_telehealth' => false],
                    ['name' => 'Medication Review', 'duration_minutes' => 20, 'is_telehealth' => true],
                ],
                'default_diagnosis_favorites' => [
                    ['code' => 'M54.5', 'description' => 'Low back pain'],
                    ['code' => 'M54.2', 'description' => 'Cervicalgia'],
                    ['code' => 'G89.29', 'description' => 'Other chronic pain'],
                    ['code' => 'M79.7', 'description' => 'Fibromyalgia'],
                    ['code' => 'G43.909', 'description' => 'Migraine, unspecified'],
                    ['code' => 'M47.816', 'description' => 'Spondylosis with radiculopathy, lumbar region'],
                    ['code' => 'G56.00', 'description' => 'Carpal tunnel syndrome, unspecified upper limb'],
                    ['code' => 'M25.50', 'description' => 'Pain in unspecified joint'],
                ],
                'default_medication_categories' => [
                    'NSAIDs', 'Muscle Relaxants', 'Neuropathic Pain Agents', 'Opioids',
                    'Topical Analgesics', 'Anticonvulsants', 'Antidepressants (Pain)',
                ],
                'default_lab_panels' => [
                    'CBC', 'CMP', 'ESR/CRP', 'Urine Drug Screen', 'HbA1c', 'Vitamin D',
                ],
                'default_plan_templates' => [
                    [
                        'name' => 'Pain Relief',
                        'monthly_price' => 119.00,
                        'annual_price' => 1199.00,
                        'visits_per_month' => 1,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 24,
                        'crisis_support' => false,
                        'badge_text' => null,
                    ],
                    [
                        'name' => 'Comprehensive Pain',
                        'monthly_price' => 219.00,
                        'annual_price' => 2199.00,
                        'visits_per_month' => 2,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 8,
                        'crisis_support' => false,
                        'badge_text' => 'Most Popular',
                    ],
                ],
                'default_intake_sections' => [
                    'demographics', 'pain_history', 'medical_history',
                    'surgical_history', 'medications', 'allergies',
                    'insurance', 'emergency_contacts', 'consent',
                ],
                'default_addons' => [
                    ['name' => 'Trigger Point Injection', 'price' => 100.00, 'billing_type' => 'one_time'],
                    ['name' => 'Joint Injection', 'price' => 150.00, 'billing_type' => 'one_time'],
                ],
            ],

            // ─── Addiction Medicine ───
            [
                'name' => 'Addiction Medicine',
                'code' => 'addiction_medicine',
                'description' => 'Substance use disorder treatment including medication-assisted treatment, counseling, and recovery support.',
                'default_screening_tools' => ['audit_c', 'phq9', 'gad7'],
                'default_appointment_types' => [
                    ['name' => 'Initial Assessment', 'duration_minutes' => 60, 'is_telehealth' => true],
                    ['name' => 'MAT Follow-Up', 'duration_minutes' => 30, 'is_telehealth' => true],
                    ['name' => 'Counseling Session', 'duration_minutes' => 50, 'is_telehealth' => true],
                    ['name' => 'Drug Screen Visit', 'duration_minutes' => 15, 'is_telehealth' => false],
                ],
                'default_diagnosis_favorites' => [
                    ['code' => 'F10.20', 'description' => 'Alcohol use disorder, moderate'],
                    ['code' => 'F10.10', 'description' => 'Alcohol use disorder, mild'],
                    ['code' => 'F11.20', 'description' => 'Opioid use disorder, moderate'],
                    ['code' => 'F14.20', 'description' => 'Cocaine use disorder, moderate'],
                    ['code' => 'F15.20', 'description' => 'Stimulant use disorder, moderate'],
                    ['code' => 'F12.20', 'description' => 'Cannabis use disorder, moderate'],
                    ['code' => 'F17.210', 'description' => 'Nicotine dependence, cigarettes'],
                    ['code' => 'F19.20', 'description' => 'Other psychoactive substance use disorder, moderate'],
                ],
                'default_medication_categories' => [
                    'Buprenorphine/Naloxone', 'Naltrexone', 'Acamprosate', 'Disulfiram',
                    'Nicotine Replacement', 'Varenicline', 'SSRIs', 'Anti-Anxiety',
                ],
                'default_lab_panels' => [
                    'CBC', 'CMP', 'Hepatic Panel', 'Urine Drug Screen',
                    'Hepatitis Panel', 'HIV', 'GGT', 'CDT',
                ],
                'default_plan_templates' => [
                    [
                        'name' => 'Recovery',
                        'monthly_price' => 129.00,
                        'annual_price' => 1299.00,
                        'visits_per_month' => 2,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 12,
                        'crisis_support' => true,
                        'badge_text' => null,
                    ],
                    [
                        'name' => 'Intensive Recovery',
                        'monthly_price' => 249.00,
                        'annual_price' => 2499.00,
                        'visits_per_month' => 4,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 4,
                        'crisis_support' => true,
                        'badge_text' => 'Most Popular',
                    ],
                ],
                'default_intake_sections' => [
                    'demographics', 'substance_use_history', 'psychiatric_history',
                    'medical_history', 'legal_history', 'social_support',
                    'medications', 'allergies', 'insurance', 'emergency_contacts', 'consent',
                ],
                'default_addons' => [
                    ['name' => 'Drug Screen (UDS)', 'price' => 25.00, 'billing_type' => 'one_time'],
                    ['name' => 'Group Therapy Session', 'price' => 30.00, 'billing_type' => 'one_time'],
                    ['name' => 'Family Counseling', 'price' => 75.00, 'billing_type' => 'one_time'],
                ],
            ],

            // ─── Neurology ───
            [
                'name' => 'Neurology',
                'code' => 'neurology',
                'description' => 'Diagnosis and management of neurological conditions including headache, epilepsy, and movement disorders.',
                'default_screening_tools' => ['phq9'],
                'default_appointment_types' => [
                    ['name' => 'New Patient Evaluation', 'duration_minutes' => 60, 'is_telehealth' => false],
                    ['name' => 'Follow-Up', 'duration_minutes' => 30, 'is_telehealth' => true],
                    ['name' => 'EEG Review', 'duration_minutes' => 15, 'is_telehealth' => true],
                    ['name' => 'Botox Injection', 'duration_minutes' => 30, 'is_telehealth' => false],
                ],
                'default_diagnosis_favorites' => [
                    ['code' => 'G43.909', 'description' => 'Migraine, unspecified'],
                    ['code' => 'G40.909', 'description' => 'Epilepsy, unspecified, not intractable'],
                    ['code' => 'G35', 'description' => 'Multiple sclerosis'],
                    ['code' => 'G20', 'description' => 'Parkinson\'s disease'],
                    ['code' => 'G56.00', 'description' => 'Carpal tunnel syndrome, unspecified'],
                    ['code' => 'G47.33', 'description' => 'Obstructive sleep apnea'],
                    ['code' => 'R51.9', 'description' => 'Headache, unspecified'],
                    ['code' => 'G62.9', 'description' => 'Polyneuropathy, unspecified'],
                ],
                'default_medication_categories' => [
                    'Anticonvulsants', 'Triptans', 'CGRP Inhibitors', 'Dopaminergics',
                    'Muscle Relaxants', 'Neuropathic Pain Agents', 'Botulinum Toxin',
                ],
                'default_lab_panels' => [
                    'CBC', 'CMP', 'TSH', 'B12', 'Folate',
                    'ESR/CRP', 'ANA', 'Vitamin D', 'HbA1c',
                ],
                'default_plan_templates' => [
                    [
                        'name' => 'Neuro Care',
                        'monthly_price' => 129.00,
                        'annual_price' => 1299.00,
                        'visits_per_month' => 1,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 24,
                        'crisis_support' => false,
                        'badge_text' => null,
                    ],
                    [
                        'name' => 'Comprehensive Neuro',
                        'monthly_price' => 229.00,
                        'annual_price' => 2299.00,
                        'visits_per_month' => 2,
                        'telehealth_included' => true,
                        'messaging_included' => true,
                        'messaging_response_sla_hours' => 8,
                        'crisis_support' => false,
                        'badge_text' => 'Most Popular',
                    ],
                ],
                'default_intake_sections' => [
                    'demographics', 'neurological_history', 'medical_history',
                    'family_history', 'medications', 'allergies',
                    'insurance', 'emergency_contacts', 'consent',
                ],
                'default_addons' => [
                    ['name' => 'EEG Interpretation', 'price' => 75.00, 'billing_type' => 'one_time'],
                    ['name' => 'Botox Treatment', 'price' => 200.00, 'billing_type' => 'one_time'],
                    ['name' => 'Sleep Study Review', 'price' => 50.00, 'billing_type' => 'one_time'],
                ],
            ],
        ];

        foreach ($specialties as $spec) {
            MasterSpecialty::updateOrCreate(
                ['code' => $spec['code']],
                [
                    'name' => $spec['name'],
                    'description' => $spec['description'] ?? null,
                    'default_screening_tools' => $spec['default_screening_tools'],
                    'default_appointment_types' => $spec['default_appointment_types'],
                    'default_diagnosis_favorites' => $spec['default_diagnosis_favorites'],
                    'default_medication_categories' => $spec['default_medication_categories'],
                    'default_lab_panels' => $spec['default_lab_panels'],
                    'default_plan_templates' => $spec['default_plan_templates'],
                    'default_intake_sections' => $spec['default_intake_sections'],
                    'default_addons' => $spec['default_addons'],
                    'is_active' => true,
                ]
            );
        }
    }
}
